### ISSUE TITLE
動画を最小化した時の操作

### ISSUE THREAD

**Issue by hidechae** [otiai10/soundhook#20]
動画を最小化した時に再生位置をいじれたり、音量調整出来ると嬉しい

**Comment by otiai10** [comment]
ﾃﾞｽﾖﾈー

**Comment by otiai10** [comment]
ブラウザキーバインドと、youtubePlayerアピ

**Comment by otiai10** [comment]
これはいけそう

**Comment by otiai10** [comment]
https://github.com/otiai10/soundhook/pull/24

**Comment by otiai10** [comment]
あと、UI的に工夫する

**Comment by otiai10** [comment]
https://github.com/otiai10/soundhook/pull/25
@hidechae

**Comment by otiai10** [comment]
o : オープン
t : ツイート
r : リピート

**Comment by otiai10** [comment]
いらんな
